#!/usr/bin/env bash

sudo yum update –y

sudo yum install -y httpd24

sudo chkconfig httpd on

# create groups
mkdir -p /var/www/html

sudo groupadd www
sudo usermod -a -G www ec2-user

#chown to group
sudo chown -R root:www /var/www

# set modes recursively
sudo chmod 2775 /var/www

sudo service httpd start